"""add resolution column to price_history

Revision ID: 46843827c354
Revises: 89e4f3dcdc86
Create Date: 2026-01-14 00:39:06.376229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46843827c354'
down_revision: Union[str, Sequence[str], None] = '89e4f3dcdc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('resolution', sa.String(length=20), server_default='daily', nullable=False))
    op.drop_constraint(op.f('uq_item_source_date'), 'price_history', type_='unique')
    op.create_index('idx_price_history_resolution', 'price_history', ['item_id', 'resolution', 'date'], unique=False)
    op.create_unique_constraint('uq_item_source_date_resolution', 'price_history', ['item_id', 'source', 'date', 'resolution'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_item_source_date_resolution', 'price_history', type_='unique')
    op.drop_index('idx_price_history_resolution', table_name='price_history')
    op.create_unique_constraint(op.f('uq_item_source_date'), 'price_history', ['item_id', 'source', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('price_history', 'resolution')
    # ### end Alembic commands ###
