"""initial schema with items system

Revision ID: 89e4f3dcdc86
Revises: 
Create Date: 2026-01-14 00:20:18.396791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89e4f3dcdc86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(length=255), nullable=False),
    sa.Column('base_name', sa.String(length=255), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('weapon_type', sa.String(length=50), nullable=True),
    sa.Column('weapon_name', sa.String(length=50), nullable=True),
    sa.Column('skin_name', sa.String(length=100), nullable=True),
    sa.Column('wear', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_stattrak', sa.Boolean(), nullable=True),
    sa.Column('is_souvenir', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_base_name'), 'items', ['base_name'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_market_hash_name'), 'items', ['market_hash_name'], unique=True)
    op.create_index(op.f('ix_items_weapon_name'), 'items', ['weapon_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('steam_id', sa.String(length=17), nullable=True),
    sa.Column('steam_profile_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_id'), 'investments', ['id'], unique=False)
    op.create_index(op.f('ix_investments_item_id'), 'investments', ['item_id'], unique=False)
    op.create_index(op.f('ix_investments_user_id'), 'investments', ['user_id'], unique=False)
    op.create_table('item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('csfloat_price', sa.Float(), nullable=True),
    sa.Column('csfloat_volume', sa.Integer(), nullable=True),
    sa.Column('csfloat_lowest_listing', sa.Float(), nullable=True),
    sa.Column('csfloat_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('buff_price', sa.Float(), nullable=True),
    sa.Column('buff_volume', sa.Integer(), nullable=True),
    sa.Column('buff_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('steam_price', sa.Float(), nullable=True),
    sa.Column('steam_volume', sa.Integer(), nullable=True),
    sa.Column('steam_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_prices_id'), 'item_prices', ['id'], unique=False)
    op.create_index(op.f('ix_item_prices_item_id'), 'item_prices', ['item_id'], unique=True)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'source', 'date', name='uq_item_source_date')
    )
    op.create_index('idx_price_history_item_date', 'price_history', ['item_id', 'date'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index('idx_price_history_item_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_item_prices_item_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_id'), table_name='item_prices')
    op.drop_table('item_prices')
    op.drop_index(op.f('ix_investments_user_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_item_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_weapon_name'), table_name='items')
    op.drop_index(op.f('ix_items_market_hash_name'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_base_name'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
